import type { PluginContext, PluginResult } from './index.js';

interface DiaryEntry {
  id: string;
  date: string;
  content: string;
  mood: string;
  tags: string[];
  createdAt: number;
}

interface DayRecord {
  messages: Array<{
    senderId: string;
    senderName: string;
    content: string;
    timestamp: number;
  }>;
  emotions: string[];
  topics: string[];
}

export class DiaryManager {
  private enabled: boolean = true;
  private autoGenerate: boolean = true;
  private generateTime: string = '23:00';
  private diaries: Map<string, DiaryEntry[]> = new Map();
  private dayRecords: Map<string, DayRecord> = new Map();
  private schedulerInterval: NodeJS.Timeout | null = null;
  private memoryThreshold: number = 50;
  private onDiaryGenerated?: (chatId: string, diary: DiaryEntry) => void;

  async initialize(config: any): Promise<void> {
    this.enabled = config.enableDiary ?? true;
    this.autoGenerate = config.autoGenerateDiary ?? true;
    this.generateTime = config.diaryGenerateTime ?? '23:00';
    this.memoryThreshold = config.diaryMemoryThreshold ?? 50;
    
    if (this.autoGenerate) {
      this.startScheduler();
    }
    
    console.log('[DiaryManager] 初始化完成, 自动生成:', this.autoGenerate, ', 记忆阈值:', this.memoryThreshold);
  }

  setOnDiaryGenerated(callback: (chatId: string, diary: DiaryEntry) => void): void {
    this.onDiaryGenerated = callback;
  }

  shouldGenerateDiary(chatId: string): boolean {
    const today = new Date().toISOString().split('T')[0];
    const recordKey = `${chatId}:${today}`;
    const record = this.dayRecords.get(recordKey);
    
    if (!record) return false;
    
    const existingDiaries = this.diaries.get(chatId) || [];
    const todayDiary = existingDiaries.find(d => d.date === today);
    
    return record.messages.length >= this.memoryThreshold && !todayDiary;
  }

  async generateSilentDiary(chatId: string): Promise<DiaryEntry | null> {
    const today = new Date().toISOString().split('T')[0];
    const recordKey = `${chatId}:${today}`;
    const record = this.dayRecords.get(recordKey);

    if (!record || record.messages.length === 0) {
      return null;
    }

    const diary = await this.createDiaryFromRecord(chatId, record);
    if (diary) {
      this.saveDiary(chatId, diary);
      console.log(`[DiaryManager] 📝 静默生成日记: ${chatId}, 消息数: ${record.messages.length}`);
      
      if (this.onDiaryGenerated) {
        this.onDiaryGenerated(chatId, diary);
      }
    }
    
    return diary;
  }

  getDayRecordCount(chatId: string): number {
    const today = new Date().toISOString().split('T')[0];
    const recordKey = `${chatId}:${today}`;
    const record = this.dayRecords.get(recordKey);
    return record?.messages.length || 0;
  }

  private startScheduler(): void {
    const checkAndGenerate = () => {
      const now = new Date();
      const [hour, minute] = this.generateTime.split(':').map(Number);
      
      if (now.getHours() === hour && now.getMinutes() === minute) {
        this.generateDailyDiaries();
      }
    };

    this.schedulerInterval = setInterval(checkAndGenerate, 60000);
  }

  async handle(ctx: PluginContext): Promise<PluginResult> {
    if (!this.enabled) {
      return { handled: false };
    }

    const { text, groupId, isGroup, client } = ctx;

    if (text.match(/\/diary\s+list/i) || text.includes('/日记 列表')) {
      return this.listDiaries(groupId);
    }

    if (text.match(/\/diary\s+today/i) || text.includes('/日记 今天')) {
      return this.getTodayDiary(groupId);
    }

    if (text.match(/\/diary\s+generate/i) || text.includes('/日记 生成')) {
      return this.generateDiary(groupId, client);
    }

    if (text.match(/\/diary/i) || text.includes('/日记')) {
      return this.showHelp();
    }

    return { handled: false };
  }

  recordActivity(chatId: string, senderId: string, senderName: string, content: string, emotion?: string): void {
    const today = new Date().toISOString().split('T')[0];
    const recordKey = `${chatId}:${today}`;
    
    if (!this.dayRecords.has(recordKey)) {
      this.dayRecords.set(recordKey, {
        messages: [],
        emotions: [],
        topics: []
      });
    }

    const record = this.dayRecords.get(recordKey)!;
    record.messages.push({
      senderId,
      senderName,
      content,
      timestamp: Date.now()
    });

    if (emotion) {
      record.emotions.push(emotion);
    }

    const topics = this.extractTopics(content);
    record.topics.push(...topics);
  }

  private extractTopics(content: string): string[] {
    const topics: string[] = [];
    const patterns = [
      /#(\S+)/g,
      /【([^】]+)】/g,
      /「([^」]+)」/g
    ];

    for (const pattern of patterns) {
      let match;
      while ((match = pattern.exec(content)) !== null) {
        topics.push(match[1]);
      }
    }

    return topics;
  }

  private async generateDailyDiaries(): Promise<void> {
    console.log('[DiaryManager] 开始生成每日日记...');
    
    for (const [recordKey, record] of this.dayRecords.entries()) {
      const [chatId] = recordKey.split(':');
      
      if (record.messages.length >= 10) {
        const diary = await this.createDiaryFromRecord(chatId, record);
        if (diary) {
          this.saveDiary(chatId, diary);
        }
      }
    }
  }

  private async generateDiary(groupId: number | undefined, client: any): Promise<PluginResult> {
    if (!groupId) {
      return { handled: true, response: '日记功能只在群聊中可用哦～' };
    }

    const chatId = `group:${groupId}`;
    const today = new Date().toISOString().split('T')[0];
    const recordKey = `${chatId}:${today}`;
    const record = this.dayRecords.get(recordKey);

    if (!record || record.messages.length === 0) {
      return { handled: true, response: '今天还没有聊天记录呢，没法写日记～' };
    }

    const diary = await this.createDiaryFromRecord(chatId, record);
    if (diary) {
      this.saveDiary(chatId, diary);
      return { handled: true, response: `📝 日记已生成！\n\n${diary.content}` };
    }

    return { handled: false, response: '生成日记失败了～' };
  }

  private async createDiaryFromRecord(chatId: string, record: DayRecord): Promise<DiaryEntry | null> {
    if (record.messages.length === 0) return null;

    const participants = new Set(record.messages.map(m => m.senderName));
    const topTopics = this.getTopItems(record.topics, 5);
    const topEmotions = this.getTopItems(record.emotions, 3);

    const date = new Date().toLocaleDateString('zh-CN', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      weekday: 'long'
    });

    const content = this.formatDiaryContent(date, record, participants, topTopics, topEmotions);

    return {
      id: `diary_${Date.now()}`,
      date: new Date().toISOString().split('T')[0],
      content,
      mood: topEmotions[0] || '平静',
      tags: topTopics,
      createdAt: Date.now()
    };
  }

  private formatDiaryContent(
    date: string,
    record: DayRecord,
    participants: Set<string>,
    topics: string[],
    emotions: string[]
  ): string {
    let content = `📅 ${date}\n\n`;
    
    content += `📊 今日统计\n`;
    content += `• 消息总数: ${record.messages.length}\n`;
    content += `• 活跃人数: ${participants.size}\n`;
    
    if (topics.length > 0) {
      content += `• 热门话题: ${topics.join('、')}\n`;
    }
    
    if (emotions.length > 0) {
      content += `• 主要情绪: ${emotions.join('、')}\n`;
    }
    
    content += `\n💬 精彩片段\n`;
    
    const highlights = record.messages
      .filter(m => m.content.length > 10 && !m.content.startsWith('/'))
      .slice(-5);
    
    for (const msg of highlights) {
      const shortContent = msg.content.length > 50 
        ? msg.content.substring(0, 47) + '...' 
        : msg.content;
      content += `• ${msg.senderName}: ${shortContent}\n`;
    }

    return content;
  }

  private getTopItems(items: string[], limit: number): string[] {
    const freq = new Map<string, number>();
    for (const item of items) {
      freq.set(item, (freq.get(item) || 0) + 1);
    }
    
    return Array.from(freq.entries())
      .sort((a, b) => b[1] - a[1])
      .slice(0, limit)
      .map(([item]) => item);
  }

  private saveDiary(chatId: string, diary: DiaryEntry): void {
    if (!this.diaries.has(chatId)) {
      this.diaries.set(chatId, []);
    }
    this.diaries.get(chatId)!.push(diary);
  }

  private listDiaries(groupId: number | undefined): PluginResult {
    if (!groupId) {
      return { handled: true, response: '日记功能只在群聊中可用哦～' };
    }

    const chatId = `group:${groupId}`;
    const diaries = this.diaries.get(chatId) || [];

    if (diaries.length === 0) {
      return { handled: true, response: '还没有日记呢～' };
    }

    const list = diaries
      .slice(-10)
      .map(d => `• ${d.date} [${d.mood}] ${d.tags.slice(0, 3).join('、')}`)
      .join('\n');

    return { handled: true, response: `📖 日记列表\n\n${list}` };
  }

  private getTodayDiary(groupId: number | undefined): PluginResult {
    if (!groupId) {
      return { handled: true, response: '日记功能只在群聊中可用哦～' };
    }

    const chatId = `group:${groupId}`;
    const today = new Date().toISOString().split('T')[0];
    const diaries = this.diaries.get(chatId) || [];
    const todayDiary = diaries.find(d => d.date === today);

    if (!todayDiary) {
      return { handled: true, response: '今天还没有日记呢，用 /diary generate 来生成吧～' };
    }

    return { handled: true, response: `📝 今日日记\n\n${todayDiary.content}` };
  }

  private showHelp(): PluginResult {
    const help = `📖 日记功能帮助

/diary today - 查看今日日记
/diary list - 查看日记列表
/diary generate - 生成今日日记

日记会在每天 ${this.generateTime} 自动生成哦～`;
    
    return { handled: true, response: help };
  }

  destroy(): void {
    if (this.schedulerInterval) {
      clearInterval(this.schedulerInterval);
    }
  }
}
